# Generated by Django 4.0.6 on 2023-03-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_table_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='created_by',
        ),
    ]
