# Generated by Django 4.0.6 on 2023-03-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_table_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='id',
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
