# Generated by Django 4.0.6 on 2023-03-24 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_alter_reservation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
