# Generated by Django 4.0.6 on 2023-03-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_reservation_number_of_people'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('-pk',)},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='client_phone',
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_phone_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
